### PR TITLE
Fixing some errors when reading and writing at the same time in the modbus adapter

### LINKED ISSUE #26: Error writing or reading in the modbus adapter
The following error may appear when reading or writing data at the same time:
Error reading registers: Unknown error
Error writing registers: Unknown error

### PR DESCRIPTION
**Pull request by angelrti**
closes #26

### CODE REVIEW

File: plugins/adapters/modbus/srcCxx/LibModbusClient.cxx [hunk 1]
```diff
@@ -46,6 +46,8 @@ void LibModbusClient::connect(const std::string& ip, unsigned int port)
                 + "> " + modbus_strerror(errno));
         throw std::runtime_error(error);
     }
+    std::string ip_address_ = ip;
+    uint16_t port_number_ = port;
```
Comment (fgaranda) [inline plugins/adapters/modbus/srcCxx/LibModbusClient.cxx:50]: Aren't you redefining these variables? Did you mean

```cpp
ip_address_ = ip;
port_number_ = port;
```

**Review by fgaranda — CHANGES_REQUESTED** [review]

File: plugins/adapters/modbus/srcCxx/LibModbusClient.cxx (hunk 1 above)
Comment (angelrti) [reply plugins/adapters/modbus/srcCxx/LibModbusClient.cxx:50]: nice catch! Although those variables are not used for any functional feature, they are not correctly assigned.

**Review by fgaranda — APPROVED** [review]
